FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY frontend/package.json ./
COPY frontend/yarn.lock ./

# Install dependencies
RUN yarn install

# Copy rest of the code
COPY frontend/ ./

EXPOSE 3000

CMD ["yarn", "start"]
