FROM node:18-alpine

WORKDIR /app

# Copy package files from the frontend context
COPY package.json ./
COPY yarn.lock ./

# Install dependencies
RUN yarn install

# Copy rest of the code
COPY . ./

EXPOSE 3000

CMD ["yarn", "start"]
